const BASE_URL = process.env.NEXT_PUBLIC_URL as string;

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: "no",
};

export const metadata = {
  title: "Space Digitalia",
  description:
    "Spesialis dalam SEO, Desain UI/UX, serta Pengembangan Aplikasi Mobile dan Web. Kami menggabungkan kreativitas dengan teknologi terbaru untuk hasil terbaik. Wujudkan visi digital Anda bersama Space Digitalia.",
  favicon: "/public/icon.png",
  authors: [{ name: "Rizki Ramadhan" }],
  sitemap: "/public/sitemap.xml",
  keywords: [
    "Space Digitalia",
    "Space",
    "Digitalia",
    "Rizki Ramadhan",
    "Rizki",
    "Ramadhan",
    "Web Design",
    "Web Development",
    "Jasa Pembuatan Website Leuwiliang",
    "Jasa Pembuatan Website Cibatok",
    "Jasa Pembuatan Website Ciampea",
    "Jasa Pembuatan Website Bogor",
    "Jasa Pembuatan Website",
    "Jasa Pembuatan Landing Page",
    "Jasa Pembuatan Website Company Profile",
    "Jasa Pembuatan Website Toko Online",
    "Jasa Pembuatan Website Blog",
    "Jasa Pembuatan Website Portfolio",
    "Jasa Pembuatan Website Landing Page",
    "Jasa Pembuatan Website Landing Page Company Profile",
    "Jasa Pembuatan Website Landing Page Toko Online",
    "Jasa Pembuatan Website Landing Page Blog",
    "Jasa Pembuatan Website Landing Page Portfolio",
    "Jasa Pembuatan Website Landing Page Landing Page Company Profile",
    "Jasa Membuat Website",
    "Jasa Membuat Landing Page",
    "Jasa Membuat Website Company Profile",
    "Jasa Membuat Website Toko Online",
    "Jasa Membuat Website Blog",
    "Jasa Membuat Website Portfolio",
    "Jasa Membuat Website Landing Page",
    "Jasa Membuat Website Landing Page Company Profile",
    "Jasa Membuat Website Landing Page Toko Online",
    "Jasa Membuat Website Landing Page Blog",
    "Jasa Membuat Website Landing Page Portfolio",
    "Jasa Membuat Website Landing Page Landing Page Company Profile",
    "Jasa Membuat Website Landing Page Landing Page Toko Online",
    "Jasa Membuat Website Landing Page Landing Page Blog",
    "Jasa Membuat Website Landing Page Landing Page Portfolio",
    "Jasa Membuat Website Landing Page Landing Page Landing Page Company Profile",
    "Jasa Membuat Website Landing Page Landing Page Landing Page Toko Online",
    "Jasa Membuat Website Landing Page Landing Page Landing Page Blog",
    "Leuwiliang",
    "Leuwiliang Digitalia",
    "Leuwiliang Web Design",
    "Leuwiliang Web Development",
    "Leuwiliang Web Agency",
    "Leuwiliang Web Studio",
    "Leuwiliang Web Company",
    "Cibatok",
    "Cibatok Digitalia",
    "Cibatok Web Design",
    "Cibatok Web Development",
    "Cibatok Web Agency",
    "Cibatok Web Studio",
    "Cibatok Web Company",
    "Ciampea",
    "Ciampea Digitalia",
    "Ciampea Web Design",
    "Ciampea Web Development",
    "Ciampea Web Agency",
    "Ciampea Web Studio",
    "Ciampea Web Company",
    "Bogor",
    "Bogor Digitalia",
    "Bogor Web Design",
    "Bogor Web Development",
    "Bogor Web Agency",
    "Bogor Web Studio",
    "Bogor Web Company",
  ],

  icons: {
    icon: [
      {
        url: "/icon.png",
        sizes: "64x64 32x32 24x24 16x16",
        type: "image/x-icon",
      },
    ],
    apple: "/icon.png",
    shortcut: "/icon.png",
    appleTouchIcon: "/icon.png",
  },

  manifest: "/manifest.json",
  metadataBase: new URL(BASE_URL),
  canonical: BASE_URL,

  other: {
    "theme-color": "#f5f5f5",
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "google-tag-manager": process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
  },

  openGraph: {
    type: "website",
    title: "Space Digitalia",
    description: "Space Digitalia",
    url: BASE_URL,
    siteName: "Space Digitalia",
    locale: "id_ID",
    images: [
      {
        url: "/icon.png",
        width: 1920,
        height: 1080,
        alt: "Icon for Space Digitalia",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Space Digitalia",
    description: "Space Digitalia",
    creator: "@rizki_ramadhan",
    site: "@rizki_ramadhan",
    images: ["/icon.png"],
  },

  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID,
  },

  robots: {
    index: true,
    follow: true,
    noarchive: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
    },
    sitemap: "https://spacedigitalia.my.id/sitemap.xml",
  },
};
